### ISSUE TITLE
"This model requires a numeric target"

### ISSUE THREAD

**Issue by CarolineLMT** [lmtUds/dav3e-beta#3]
Beim Training der Regression kommt oben genannter Fehler. Das liegt an undefined Werten im categorical array, der für's Training gebraucht wird, eine mögliche Lösung von TB, die aber auch zu anderen Problemen führen könnte (deshalb sollte das noch reichhaltig getestet werden) in classes\project.m zwischen Zeil 347 

            data.data(:,invalid) = [];

und 348 

            obj.mergedFeatureData = data;

noch folgende hinzufügen:

            data.groupings(isundefined(data.groupings)) = '<ignore>';

**Comment by lmtUds** [comment]
Fehler mittlerweile gelöst.
