### ISSUE TITLE
Curve Fitting Toolbox wird benötigt

### ISSUE THREAD

**Issue by manuelbastuck** [lmtUds/dav3e-beta#6]
Für das gaussfit-Feature wird die Curve Fitting Toolbox benötigt, die sich derzeit nicht in der Liste der benötigten Toolboxen befindet.

**Comment by manuelbastuck** [comment]
Genaugenommen brauchen wir "nur" `fit`, also mindestens eine dieser Toolboxen:
~~~
'fit' requires one of the following:
  Curve Fitting Toolbox
  Model-Based Calibration Toolbox
  Predictive Maintenance Toolbox
~~~

**Comment by lmtUds** [comment]
Toolbox wurde in Readme hinzugefügt.
